---
port: 8000
log:
  level: debug
store:
  provider: alicloud
  alicloud:
    bucket: blobber-test
    region: eu-central-1
    endpoint: "oss-eu-central-1.aliyuncs.com"
auth:
  provider: env
  api_token_env_var: "BLOBBER_API_TOKEN"
