---
port: 8000
log:
  level: debug
store:
  provider: azure
  azure:
    account_name: "blobbertest"
    container: "blobber-test"
    endpoint: "https://blobbertest.blob.core.windows.net/"
auth:
  provider: env
  api_token_env_var: "BLOBBER_API_TOKEN"
