---
port: 8080
log_level: debug
blob_provider: gcp
gcp_config:
  bucket: blobber-test
  project_id: blobber-477713
  credentials_path: /home/timgluz/Documents/blobber-test-gcp-creds.json
auth:
  store_type: env
  api_token_env_var: "BLOBBER_API_TOKEN"
