---
port: 8080
log_level: debug
blob_provider: azure
azure_config:
  account_name: "blobbertest"
  container: "blobber-test"
  endpoint: "https://blobbertest.blob.core.windows.net/"
auth:
  store_type: env
  api_token_env_var: "BLOBBER_API_TOKEN"
