---
port: 8080
log_level: debug
blob_provider: alicloud
alicloud_config:
  bucket: blobber-test
  region: eu-central-1
  endpoint: "oss-eu-central-1.aliyuncs.com"
auth:
  store_type: env
  api_token_env_var: "BLOBBER_API_TOKEN"
