---
port: 8080
log:
  level: info
store:
  provider: s3
  s3:
    bucket: wasserspiegel-dev
    region: auto
    endpoint: "https://0d10b377f57cf5a47fd9ca9b8ba2d5c2.r2.cloudflarestorage.com"
    use_path_style: true
auth:
  store_type: env
  api_token_env_var: "BLOBBER_API_TOKEN"
